# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

[package]
name = "Mandelbrot"
version = "0.0.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.37.0", features = ["bundled"] }
threadpool = { version = "1.8.1" }
