# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: main
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 6
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # renovate:
          - runner: macos-15
            os: macos
            arch: aarch64
          # renovate:
          - runner: ubuntu-24.04
            os: linux
            arch: x86-64
          # renovate:
          - runner: ubuntu-24.04-arm
            os: linux
            arch: aarch64
          # renovate:
          - runner: windows-11-arm
            os: windows
            arch: aarch64
          # renovate:
          - runner: windows-2025
            os: windows
            arch: x86-64
      fail-fast: false
    name: Build on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        shell: pwsh
        run: cargo build --release

      - name: Inspect the build directory
        shell: pwsh
        run: ls target/release

      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mandelbrot.${{ matrix.os }}.${{ matrix.arch }}
          path: |
            target/release/Mandelbrot
            target/release/Mandelbrot.exe
            target/release/Mandelbrot.pdb
          if-no-files-found: 'ignore'

  release:
    runs-on: ubuntu-24.04
    needs: [ build ]
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: Download macOS AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: mandelbrot.macos.aarch64
          path: ./tmp/macos/aarch64
      - name: Download Linux AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: mandelbrot.linux.aarch64
          path: ./tmp/linux/aarch64
      - name: Download Linux x86-64 artifact
        uses: actions/download-artifact@v4
        with:
          name: mandelbrot.linux.x86-64
          path: ./tmp/linux/x86-64
      - name: Download Windows AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: mandelbrot.windows.aarch64
          path: ./tmp/windows/aarch64
      - name: Download Windows x86-64 artifact
        uses: actions/download-artifact@v4
        with:
          name: mandelbrot.windows.x86-64
          path: ./tmp/windows/x86-64

      - name: Move the packages
        shell: pwsh
        run: scripts/Move-Packages.ps1

      - name: Prepare the release notes
        uses: ForNeVeR/ChangelogAutomation.action@v2
        with:
          input: ./CHANGELOG.md
          output: ./release-notes.md
          format: Markdown
      - name: Upload the release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: ./release-notes.md

      - name: List the package directory contents
        shell: pwsh
        run: ls package
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./package/*.zip
          body_path: ./release-notes.md

  encoding:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Verify encoding
        shell: pwsh
        run: Install-Module VerifyEncoding -Repository PSGallery -RequiredVersion 2.2.0 -Force && Test-Encoding

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: REUSE license check
        uses: fsfe/reuse-action@v5
